### ISSUE TITLE
What is the correct value of STEP_TYPE_DEFAULT?

### ISSUE THREAD

**Issue by tidyoux** [icon-project/icon-service#109]
What is the correct value of `STEP_TYPE_DEFAULT` ?

100_000 or 1_000_000 ?

**Comment by goldworm-icon** [comment]
100_000 is correct.
step_price is 10 ** 10.
Fee of a default icx transfer transaction == 10 ** 5 * 10 ** 10 == 10 ** 15 loop == 0.001 icx

**Comment by tidyoux** [comment]
What about t-bears ?
I send transaction with 100_000 stepLimit, it returns "Step limit too low".
