### ISSUE TITLE
What is the correct value of STEP_TYPE_DEFAULT in T-Bears?

### ISSUE THREAD

**Issue by tidyoux** [icon-project/icon-service#110]
100_000 is correct
step_price is 10 ** 10
1 icx == 10 ** 18 loop

Fee of a default icx transfer transaction == 10 ** 5 * 10 ** 10 == 10 ** 15 loop == 0.001 icx

_Originally posted by @goldworm-icon in https://github.com/icon-project/icon-service/issues/109#issuecomment-478003923_

@goldworm-icon Thanks.

What about t-bears ?
I send transaction with 100_000 stepLimit, it returns "Step limit too low".
And i find some code (iconservice/builtin_scores/governance/governance.py):
```python
def _set_initial_step_costs(self):
        initial_costs = {
            STEP_TYPE_DEFAULT: 1_000_000,
...
```

**Comment by sink772** [comment]
T-Bears has the initial step costs table as you could find those in the iconservice builtin governance code. However, in case of ICON Mainnet, we've updated the step costs table with the default 100_000. You can find the latest governance code in https://github.com/icon-project/governance/blob/master/governance/governance.py#L536.
We are preparing a T-Bears docker image that would have the same step costs table with the Mainnet. Stay tuned!

**Comment by tidyoux** [comment]
@sink772 That's great, thanks!
