### ISSUE TITLE
Will next Mainnet release enable deployment of one SCORE via another SCORE?

### ISSUE THREAD

**Issue by mr-rooftop** [icon-project/icon-service#471]
Given the wonderful [MultisigWallet](https://github.com/icon-project/multisig-wallet), it would make sense that one SCORE can deploy a different SCORE. 

Also, different architectures that use multiple separate SCOREs could profit from this possibility as new SCOREs could be dynamically deployed.

Is such feature planned for future releases (maybe even next mainnet release)?

**Comment by goldworm-icon** [comment]
The next version will not contain the feature you mentioned.
I think your suggestion is reasonable, but there are lots of more important things to do.
So it seems difficult to support that feature right now, maybe until this year.
But we will do our best to support the feature in the future.
Thank you for you interest in ICON.

**Comment by mr-rooftop** [comment]
This feature would also be great to fully realize the potential of the MulitsigWallet.

Currently, the initial owner/deployer of a contract can always update a contract, even when one tries to implement an owner ship feature with multiple owners.
There is no way to prevent the wallet that initially deployed the SCORE to update the SCORE.

Therefore there is no possibility to truly remove the single-point of failure that the deploying wallet poses.

Thanks for answering and your work in ICON.
