### ISSUE TITLE
Context rollback without revert in SCORE ?

### ISSUE THREAD

**Issue by Spl3en** [icon-project/icon-service#508]
Hello ICON Team,

For context, here's my use case : I'm doing a multisig wallet that can process multiple sub-transaction in a single transaction.
If a sub-transaction fails, I'd like to cancel already executed sub-transactions.

For doing so, I'm looking for a way to rollback an `IconScoreContext` to a previous state when writing a SCORE contract.

I could do that with the `revert` method, but the issue with that API is that it also throws and stop the SCORE method.
I'd like to call a `rollback` method that does the same than `revert` but also keeps executing further operations, so I can cancel all previous operations and keep executing the transaction. As I call external SCOREs before the rollback, I cannot reset the variables manually.
 
Is there a way to do what I want in the current version ?

The current `IconScoreContext` doesn't seem accessible from the SCORE environnent. It's available in `self._context` but as it isn't documented, I don't think we're supposed to access it.

Thank you!

**Comment by goldworm-icon** [comment]
IconScoreContext can not be accessible from score because it has critical functions and attributes used for tx processing in iconservice.

The rollback feature that you want is not supported in the current version.
A simple solution that I can suggest is to check precondition before executing sub-transactions to avoid sub-tx failure and revert.
But I guess you've already thought this kind of solutions.

**Comment by Spl3en** [comment]
Thanks for the quick reply @goldworm-icon , much appreciated 👍 

Unfortunately yes I thought about preconditions, but as each sub-transactions are called to external contracts defined by the multisig user, I cannot control beforehand what the target contract will be and what the user is going to do.

Alternatively to a "rollback" method, another way would be to implement it would be a method that is called after the revert rollback, Such as : 

```py
REVERT_FOR_NO_REASON = 1234

@external
def external_method(self):
  self.var.set("some value")
  revert("My revert message", code=REVERT_FOR_NO_REASON)

# SCORE method similar to on_install and on_update
def on_revert(self, revert_code: int):
  # method called everytime the SCORE failed,
   # all previous operations have already been rollbacked
  if revert_code == REVERT_FOR_NO_REASON:
     # handle the "REVERT_FOR_NO_REASON" revert
     self.var.set("error")
```

**Comment by ajaya-man** [comment]
Not sure if my comment would help.

If the external contracts revert the transaction we can catch those revert transactions and handle in our own way. 
A sample contract I deployed to test this functionality.
https://bicon.tracker.solidwallet.io/transaction/0xba0e83b5f5dd996e7db4bf4a9451a35f3eada209b5be886f5c7dfa61dcc11f6a#events

https://bicon.tracker.solidwallet.io/contract/cx8f49fa5ffdd2727c67729fcd568a50abe060edc7#code
I created this contract which is being reverted by the other contract, which is being handled and created a event log from the revert message.

**Comment by Spl3en** [comment]
Thanks for helping @ajaya-man !

Unfortunately the issue is not catching external contracts reverts (which I already do), but to rollback previous calls to other external contracts.

For instance, here's what may happen in a single transaction of a multisig call : 

- Sub-Transaction n°1 calls method1 to contract1 : it sends 100 ICX from A to B
- Sub-Transaction n°2 calls method2 to contract2 : it sends 200 ICX from A to B
- Sub-Transaction n°3 calls method1 to contract1 : it fails.

Now, I caught the subtx n°3, but how can I also send back the 300 ICX from B to A ?
As there is no "cancel all previous operations" and no way to do that except using revert() in the current contract, I have no solution.

**Comment by sink772** [comment]
Hello, @Spl3en !
It seems the single transaction in your scenario does too many jobs during its lifetime, which should be divided into several transactions.  Or the first and second sub-transactions could simply mark approval states rather than sending ICX directly to B, which makes B can withdraw the funds in later transactions without involving the multisig.

Anyway I believe your scenario cannot be directly solved with the current revert() mechanism.  I don't think it will be resolved in the future either, since "all or nothing" idiom is the basics of transaction.

**Comment by Spl3en** [comment]
Hi @sink772 !
Thanks for the answer and the interesting ideas. 

I'm definitely looking for a way to do all these subtx atomically in the "all or nothing" manner, except that I need to write somewhere that "nothing" happened somehow. Right now, only the person who initiated the transaction is aware of its failure, there is no way to share the failure in the system.

Unfortunately, I cannot subdivides the transaction if it can't be solved atomically without defeating the main purpose of the multisig wallet. Let's say the multisig is used in a DAO and the employees A and B agree to pay themselves 300 ICX each, but they don't realize there's only 500 ICX in the multisig balance. Hence only the first employee (first subtx) will be paid, and the other will receive the "Not enough balance" error. I don't see that as an acceptable solution in reality.


Alternatively, would it be possible to emulate the subtxs without writing their results to the SCORE database ? Like using a temporary `IconScoreContext` ? 

Let's say I write something like that : 

```py
try:
  for subtx in subtxs:
    emulate(subtx.execute())
catch BaseException as e:
  # An error happened during one of the subtx execution
  self.system_error.set(f"Cannot execute : {e}")
  return

# Now that we made sure all transactions can be executed alltogether, actually write it to database
for subtx in subtxs:
    subtx.execute()
```


For now, I will revert the transaction and keep the transaction unsolvable.

**Comment by sink772** [comment]
That's exactly what `debug_estimateStep()` is doing, but this interface can only be used from external calls, not from SCOREs.

BTW, if you call your scenario with the following sequence,
```
MultiSig ━━> SCORE_A.entry() ━┳━> SCORE_1.method1() -- Success
                              ┣━> SCORE_2.method2() -- Success
                              ┗━> SCORE_3.method3() -- Failure!
```
`SCORE_A.entry()` will be reverted when `SCORE_3.method3()` fails, in turn, MultiSig can catch the revert exception and write the failure state. Isn't it what you want to achieve?

**Comment by Spl3en** [comment]
Thanks @sink772, that sounds really interesting, I didn't though about that !

I tried to self call the multisig wallet instead of using another SCORE, and it works perfectly !

```py
from iconservice import *
from .checks import *

DESTINATION = Address.from_string(f"hx{'1'*40}")


class ExecuteProxyInterface(InterfaceScore):
    @interface
    def execute_proxy(self) -> None:
        pass


class RevertTest(IconScoreBase):
    def __init__(self, db: IconScoreDatabase) -> None:
        super().__init__(db)

    def on_install(self) -> None:
        super().on_install()

    def on_update(self) -> None:
        super().on_update()

    @catch_error
    @external(readonly=True)
    def get_balance(self) -> str:
        return str(self.icx.get_balance(DESTINATION) // 10**18)

    @catch_error
    @external
    def execute_transaction_with_proxy(self) -> None:
        proxy = self.create_interface_score(self.address, ExecuteProxyInterface)
        try:
            proxy.execute_proxy()
        except BaseException as e:
            Logger.warning(f"Caught exception from proxy contract : {e}")
            Logger.warning(f"Balance after exception : {self.get_balance()}")

    @catch_error
    @external
    def execute_transaction_without_proxy(self) -> None:
        proxy = self.create_interface_score(self.address, ExecuteProxyInterface)
        try:
            self._execute_subtxs()
        except BaseException as e:
            Logger.warning(f"Caught exception from base contract : {e}")
            Logger.warning(f"Balance after exception : {self.get_balance()}")

    @catch_error
    @external
    @only_wallet
    def execute_proxy(self) -> None:
        self._execute_subtxs()

    def _execute_subtxs(self) -> None:
        # Simulate sending multiple transactions
        Logger.warning("SubTx 1")
        self.icx.transfer(DESTINATION, 100 * 10**18)
        Logger.warning("SubTx 2")
        self.icx.transfer(DESTINATION, 200 * 10**18)
        # This one is supposed to fail
        Logger.warning("SubTx 3")
        self.icx.transfer(DESTINATION, 100000000 * 10**18)

    @payable
    def fallback(self):
        Logger.warning(f"Received {self.msg.value/10**18} ICX!")
        pass
```

My tbears log outputs the following after calling `execute_transaction_with_proxy` :

```
2020-09-03 00:10:25,089 1824 139825334769408 WARNING main.py(94) LOG SubTx 1
2020-09-03 00:10:25,089 1824 139825334769408 WARNING main.py(96) LOG SubTx 2
2020-09-03 00:10:25,090 1824 139825334769408 WARNING main.py(99) LOG SubTx 3
2020-09-03 00:10:25,090 1824 139825334769408 WARNING main.py(73) LOG Caught exception from proxy contract : Out of balance (11)
2020-09-03 00:10:25,090 1824 139825334769408 WARNING main.py(74) LOG Balance after exception : 0
```

My tbears log outputs the following after calling `execute_transaction_without_proxy` :

```
2020-09-03 00:11:35,200 1824 139825334769408 WARNING main.py(94) LOG SubTx 1
2020-09-03 00:11:35,201 1824 139825334769408 WARNING main.py(96) LOG SubTx 2
2020-09-03 00:11:35,201 1824 139825334769408 WARNING main.py(99) LOG SubTx 3
2020-09-03 00:11:35,201 1824 139825334769408 WARNING main.py(83) LOG Caught exception from base contract : Out of balance (11)
2020-09-03 00:11:35,202 1824 139825334769408 WARNING main.py(84) LOG Balance after exception : 300
```

This is exactly the behavior I needed.

Thanks again @sink772 for this clever idea.
